### ISSUE TITLE
테스트 관련 설정 및 가이드라인 코드 작성

### ISSUE THREAD

**Issue by sujin-park** [depromeet/11th_5team_fe#1]
## Overview

- Jest, React Testing Library 추가 및 설정. 
- 간단한 가이드라인 코드 작성 

## Type

- [x] 새로운 기능

## Motivation

- 안전하고 빠른 리팩터링 가능하도록 테스트 환경 구축 

## Checklist

- [x] Type에 체크하지 않은 체크 박스를 삭제하셨나요?
- [x] 기능에 대해 필요한 내용을 올바르게 설명했나요?

**Comment by guymoon** [comment]
테스트 작성 어려우실 때 아래 링크 참조하시면 좋을 것 같아 공유드립니다~
https://testing-playground.com/
