### ISSUE TITLE
소셜 로그인

### ISSUE THREAD

**Issue by sujin-park** [depromeet/11th_5team_fe#2]
### 🔖 ISSUE 종류를 선택하세요

- [x] Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Release
- [ ] Misc (docs, test, style, ...)

### 🔖 체크리스트
- [ ]

**Comment by guymoon** [comment]
Redirect URI를 어떻게 설정하면 좋을까요? 아직 페이지에 대해 이야기하지 못한 것 같아 고민이네용..

**Comment by guymoon** [comment]
나중에 애플 출시하려면 애플 로그인 필수라고 합니다. 현재 버전에서는 카카오 로그인만 하기로 했지만 추후에 추가 할 필요가 있을 것 같습니다.
