### ISSUE TITLE
Route Guard 추가 및 Page 구조 추가

### ISSUE THREAD

**Issue by sujin-park** [depromeet/11th_5team_fe#26]
## Overview

- 현재 와이어프레임 기준으로 pages 에 전반적인 Route 를 설정
- 로그인 페이지, 공유받은 상세 페이지, 편지 페이지를 제외하고 모두 인증이 필요하기 때문에 Route Guard 추가

## Type

✅ 새로운 기능

## Checklist

- [x] pages/ 에 페이지 기준으로 Route 추가
- [x] #56

**Comment by sangbooom** [comment]
> 현재 와이어프레임 기준으로 pages 에 전반적인 Route 를 설정
어떤식으로 진행하면 좋을까요?

**Comment by sujin-park** [comment]
요거는 미리 구조가 잡혀있으면 이후에 페이지 작업하기 편할 것 같아서 추가했는데, 화요일에 모여서 한번 쭉 정리하면 어떨까요?

**Comment by guymoon** [comment]
네네 좋습니다 :) CORS도 같이 화요일에 보기로 했어요~
